name: Release Bob Plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update Version Numbers
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          # Try to determine the default branch
          DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
          echo "Default branch is: $DEFAULT_BRANCH"
          
          git fetch origin $DEFAULT_BRANCH
          git checkout $DEFAULT_BRANCH
          node scripts/bump-version.js $VERSION "Release version $VERSION"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/info.json appcast.json
          git commit -m "Bump version to $VERSION"
          git push origin $DEFAULT_BRANCH

      - name: Create Release Directory
        run: |
          mkdir -p release
          cp -r src/* release/
          cd release && zip -r ../bob-plugin-elevenlabs.bobplugin *

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: bob-plugin-elevenlabs.bobplugin
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 